"""
report_exporter.py - Generate comprehensive DOCX reports from IdeaGraph results.
"""

from __future__ import annotations
from io import BytesIO
from typing import Any, Dict, List, Optional

try:
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False


def generate_report(
    results: Dict[str, Any],
    tournament_data: Optional[Dict[str, Any]] = None,
    papers: Optional[List[Dict[str, Any]]] = None,
    username: str = "Researcher",
) -> bytes:
    """Generate a comprehensive DOCX report. Returns bytes for download."""
    if not HAS_DOCX:
        raise ImportError("python-docx is required for report generation")

    doc = Document()

    # ── Title ────────────────────────────────────────────────────────────
    title = doc.add_heading("IdeaGraph Research Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    topic = results.get("topic", "Research Ideas")
    doc.add_paragraph(f"Topic: {topic}").alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(f"Generated by: {username}").alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph("")

    # ── Executive Summary ────────────────────────────────────────────────
    doc.add_heading("Executive Summary", level=1)
    ideas = results.get("ideas", [])
    stats = results.get("stats", {})
    coverage = results.get("coverage", 0)

    summary = (
        f"This report presents {len(ideas)} research ideas generated by the IdeaGraph "
        f"multi-agent ideation system for the topic \"{topic}\". "
        f"The Quality-Diversity archive achieved {coverage:.1%} coverage across "
        f"7 methodology types and 3 novelty levels. "
    )
    if stats:
        summary += (
            f"The pipeline ran {stats.get('iterations', '?')} iterations, "
            f"attempting {stats.get('ideas_attempted', '?')} ideas "
            f"in {stats.get('elapsed_seconds', 0):.0f} seconds. "
            f"Mean quality: {stats.get('quality_mean', 0):.3f}, "
            f"max quality: {stats.get('quality_max', 0):.3f}."
        )
    doc.add_paragraph(summary)

    # ── Ideas ────────────────────────────────────────────────────────────
    doc.add_heading("Research Ideas", level=1)
    sorted_ideas = sorted(ideas, key=lambda x: x.get("quality_score", 0), reverse=True)

    for i, idea in enumerate(sorted_ideas, 1):
        q = idea.get("quality_score", 0)
        doc.add_heading(f"{i}. {idea.get('title', 'Untitled')} (q={q:.3f})", level=2)

        meta = (
            f"Methodology: {idea.get('methodology_type', '?').replace('_', ' ').title()} | "
            f"Novelty: {idea.get('novelty_level', '?').capitalize()} | "
            f"Strategy: {idea.get('source_strategy', '?')}"
        )
        p = doc.add_paragraph(meta)
        p.runs[0].font.size = Pt(9)
        p.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        for field_name, label in [
            ("motivation", "Motivation"), ("method", "Method"),
            ("hypothesis", "Hypothesis"), ("resources", "Resources"),
            ("expected_outcome", "Expected Outcome"),
            ("risk_assessment", "Risk Assessment"),
        ]:
            content = idea.get(field_name, "")
            if content:
                p = doc.add_paragraph()
                run = p.add_run(f"{label}: ")
                run.bold = True
                p.add_run(content)

        # Probe scores
        scores = idea.get("probe_scores") or {}
        if scores:
            score_text = " | ".join(f"{k.capitalize()}: {v:.2f}" for k, v in scores.items())
            p = doc.add_paragraph(f"Probe Scores: {score_text}")
            p.runs[0].font.size = Pt(9)

        doc.add_paragraph("")  # spacer

    # ── Debate Results ───────────────────────────────────────────────────
    if tournament_data:
        doc.add_heading("Tournament Debate Results", level=1)
        champion = tournament_data.get("champion_title", "")
        if champion:
            doc.add_paragraph(f"Champion: {champion}").runs[0].bold = True
        doc.add_paragraph(
            f"Entrants: {tournament_data.get('entrant_count', 0)} | "
            f"Matches: {tournament_data.get('total_matches', 0)} | "
            f"Rounds: {len(tournament_data.get('rounds', []))}"
        )

        for ri, rd in enumerate(tournament_data.get("rounds", [])):
            doc.add_heading(f"Round {ri + 1}", level=2)
            for mi, m in enumerate(rd):
                title_a = ((m.get("idea_a") or {}).get("title") or "A")[:50]
                title_b = ((m.get("idea_b") or {}).get("title") or "B")[:50]
                winner = title_a if m.get("winner_side") == "a" else title_b
                doc.add_paragraph(
                    f"Match {mi+1}: {title_a} vs {title_b} — Winner: {winner[:40]}",
                    style="List Bullet",
                )

    # ── Papers ───────────────────────────────────────────────────────────
    if papers:
        doc.add_heading("Generated Papers", level=1)
        for p in papers:
            doc.add_heading(p.get("idea_title", "Paper")[:60], level=2)
            content = p.get("paper_markdown") or p.get("content", "")
            # Add first 500 chars of paper content
            if content:
                doc.add_paragraph(content[:500] + ("..." if len(content) > 500 else ""))

    # ── Save ─────────────────────────────────────────────────────────────
    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
