"""
sharing.py - Public share links for research ideas.

Provides:
  - create_share_url(): generates a public token + URL for an idea
  - render_shared_idea_page(): beautiful public display page
  - build_share_meta(): OpenGraph meta tags for social sharing
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import streamlit as st

import db


def get_base_url() -> str:
    """Get the base URL for share links."""
    # In production, set APP_BASE_URL env var
    import os
    return os.getenv("APP_BASE_URL", "http://localhost:8510")


def create_share_url(user_id: int, idea: Dict[str, Any], topic: str = "") -> str:
    """Create a public share URL for an idea."""
    token = db.create_share_token(user_id, idea, topic)
    base = get_base_url()
    return f"{base}/?share={token}"


def render_shared_idea_page(token: str) -> bool:
    """
    Render a beautiful public landing page for a shared idea.
    Returns True if the idea was found and rendered, False otherwise.
    """
    data = db.get_shared_idea(token)
    if not data:
        st.error("Shared idea not found or has been removed.")
        return False

    idea = data.get("idea", {})
    topic = data.get("topic", "Research")
    views = data.get("views", 0)
    likes = data.get("likes", 0)
    created = data.get("created_at", "")[:10]

    # Hero section
    st.markdown(
        f"""
        <div style='background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    padding: 40px; border-radius: 12px; color: white; margin-bottom: 20px;'>
            <div style='font-size: 12px; opacity: 0.9; letter-spacing: 2px; text-transform: uppercase;'>
                Research Idea • {topic[:50]}
            </div>
            <h1 style='margin: 10px 0; font-size: 28px; color: white;'>
                {idea.get('title', 'Untitled')[:100]}
            </h1>
            <div style='font-size: 14px; opacity: 0.85;'>
                👁️ {views} views · ❤️ {likes} likes · {created}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Quality + metadata
    q = idea.get("quality_score", 0)
    badge_color = "#2ecc71" if q >= 0.7 else "#f39c12" if q >= 0.5 else "#e74c3c"
    badge_text = "Excellent" if q >= 0.7 else "Good" if q >= 0.5 else "Experimental"

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Quality", f"{q:.2f}")
    col2.metric("Type", (idea.get("methodology_type") or "?").replace("_", " ").title()[:15])
    col3.metric("Novelty", (idea.get("novelty_level") or "?").capitalize())
    col4.metric("Rating", badge_text)

    # Content sections
    st.markdown("### 💡 Motivation")
    st.write(idea.get("motivation", "N/A"))

    st.markdown("### 🔬 Method")
    st.write(idea.get("method", "N/A"))

    st.markdown("### 🎯 Hypothesis")
    st.write(idea.get("hypothesis", "N/A"))

    with st.expander("See more details"):
        st.markdown("**Resources**")
        st.write(idea.get("resources", "N/A"))
        st.markdown("**Expected Outcome**")
        st.write(idea.get("expected_outcome", "N/A"))
        st.markdown("**Risk Assessment**")
        st.write(idea.get("risk_assessment", "N/A"))

    # Like button
    st.divider()
    action_col1, action_col2, action_col3 = st.columns([1, 1, 2])
    with action_col1:
        if st.button(f"❤️ Like ({likes})", type="primary", use_container_width=True):
            new_likes = db.like_shared_idea(token)
            st.success(f"Thanks! Now at {new_likes} likes.")
            st.rerun()
    with action_col2:
        share_link = f"{get_base_url()}/?share={token}"
        st.code(share_link, language=None)
    with action_col3:
        st.info("Generated by **IdeaGraph** — AI-powered research ideation")
        if st.button("Try IdeaGraph Free →", type="secondary"):
            st.session_state.clear()
            st.rerun()

    return True


def build_share_meta(idea: Dict[str, Any], topic: str) -> str:
    """Build OpenGraph HTML meta tags for social sharing."""
    title = idea.get("title", "Research Idea")[:100]
    description = (idea.get("motivation", "") or idea.get("method", "") or "")[:200]

    return f"""
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:type" content="article">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{description}">
    """
