"""
agents/paper_generator.py - Generates structured paper drafts from research ideas.

Produces markdown papers with: Abstract, Introduction, Related Work,
Method, Expected Results, and Limitations sections.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

import config
from agents.base_agent import BaseAgent
from models.idea import Idea


class PaperGenerator(BaseAgent):
    """Generates structured academic paper drafts from top-ranked ideas."""

    def __init__(self):
        super().__init__(temperature=0.3)  # low temp for coherent writing

    def generate_paper(
        self, idea: Idea, dag_summary: Dict[str, Any] = None,
        debate_history: List[Dict] = None,
    ) -> str:
        """Generate a full paper draft as markdown. One LLM call per section."""
        sections = []

        # Header
        sections.append(f"# {idea.title}\n")

        # Metadata
        meta = (
            f"**Methodology:** {(idea.methodology_type or 'N/A').replace('_', ' ').title()} | "
            f"**Novelty:** {(idea.novelty_level or 'N/A').capitalize()} | "
            f"**Quality Score:** {idea.quality_score:.2f}"
        )
        if idea.debate_rank:
            meta += f" | **Debate Rank:** #{idea.debate_rank}"
        sections.append(meta + "\n")

        # Build context strings
        related_work_ctx = self._build_related_work_context(dag_summary) if dag_summary else ""
        debate_ctx = self._build_debate_context(debate_history) if debate_history else ""

        # Generate each section
        section_specs = [
            ("Abstract", 512, f"Write a concise abstract (150-250 words) for this research idea.\n\n{idea.to_prompt_str()}"),
            ("1. Introduction", 1024, (
                f"Write the Introduction section. Cover: problem motivation, research gap, "
                f"proposed approach, and key contributions.\n\n"
                f"Motivation: {idea.motivation}\nMethod overview: {idea.method}\n"
                f"Hypothesis: {idea.hypothesis}"
            )),
            ("2. Related Work", 1024, (
                f"Write the Related Work section. Discuss existing approaches and position "
                f"this work relative to the literature.\n\n"
                f"Research area: {idea.title}\nMethod: {idea.method}\n\n"
                f"Relevant papers from the knowledge graph:\n{related_work_ctx or 'No specific papers available.'}"
            )),
            ("3. Proposed Method", 1536, (
                f"Write the Method section. Describe the technical approach in detail "
                f"with clear algorithmic steps.\n\n"
                f"Method summary: {idea.method}\n"
                f"Resources needed: {idea.resources}\n"
                f"{debate_ctx}"
            )),
            ("4. Expected Results", 768, (
                f"Write the Expected Results section. Describe experimental setup, "
                f"baselines, evaluation metrics, and anticipated outcomes.\n\n"
                f"Hypothesis: {idea.hypothesis}\n"
                f"Expected outcome: {idea.expected_outcome}\n"
                f"Resources: {idea.resources}"
            )),
            ("5. Limitations and Future Work", 512, (
                f"Write the Limitations section. Discuss potential weaknesses, "
                f"assumptions, and directions for future work.\n\n"
                f"Risk assessment: {idea.risk_assessment}\n"
                f"{debate_ctx}"
            )),
        ]

        system = (
            "You are an academic paper writer producing a research paper for a top "
            "AI conference (NeurIPS/ICML quality). Write in formal academic prose. "
            "Be specific and technical. Do not use filler phrases."
        )

        for section_name, max_tokens, prompt in section_specs:
            text = self._call(system, prompt, max_tokens=max_tokens, temperature=0.3)
            sections.append(f"## {section_name}\n\n{text}\n")

        # Footer
        sections.append("---")
        sections.append(f"*Generated by IdeaGraph Paper Generator*")
        sections.append(
            f"*Source: Strategy {idea.source_strategy} | "
            f"Quality: {idea.quality_score:.3f}"
            + (f" | Debate Rank: #{idea.debate_rank}" if idea.debate_rank else "")
            + "*"
        )

        return "\n\n".join(sections)

    def _build_related_work_context(self, dag_summary: Dict[str, Any]) -> str:
        """Extract relevant papers from DAG summary for Related Work."""
        papers = dag_summary.get("papers", [])
        if not papers:
            return ""

        lines = []
        for p in papers[:15]:
            title = p.get("title", "Untitled")
            year = p.get("year", "")
            cluster = p.get("cluster", "")
            lines.append(f"- {title} ({year}), Cluster {cluster}")
        return "\n".join(lines)

    def _build_debate_context(self, debate_history: List[Dict]) -> str:
        """Extract key arguments from debates for Method/Limitations context."""
        if not debate_history:
            return ""

        lines = ["Key points from debate:"]
        for entry in debate_history[:5]:
            role = entry.get("role", "")
            arg = entry.get("argument", "")[:200]
            lines.append(f"- [{role}] {arg}")
        return "\n".join(lines)
